
name: 部署文档

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./press/
    steps:
      - name: Checkout  
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true
          
      - name: 缓存 node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
            
      - name: 构建文档   
        run: |
          npm install
          npm run docs:build
          > src/.vuepress/dist/.nojekyll
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'

#       - name: 部署文档  
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           BRANCH: gh-pages
#           FOLDER: press/src/.vuepress/dist
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: 部署文档 
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: press/src/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
